"""temp_migration

Revision ID: 9b4eac5d3af5
Revises: 4c30519e903c
Create Date: 2025-05-24 18:16:03.990664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4eac5d3af5'
down_revision: Union[str, None] = '4c30519e903c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_movies', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_movies', 'created_at')
    # ### end Alembic commands ###
