"""temp_migration

Revision ID: ce3f0a317cf6
Revises: 9b4eac5d3af5
Create Date: 2025-06-05 16:15:08.899689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce3f0a317cf6"
down_revision: Union[str, None] = "9b4eac5d3af5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activation_tokens",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "password_reset_tokens",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "refresh_tokens",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("refresh_tokens", "created_at")
    op.drop_column("password_reset_tokens", "created_at")
    op.drop_column("activation_tokens", "created_at")
    # ### end Alembic commands ###
