[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Serhii <serhii.domik@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
sqlalchemy = "^2.0.36"
pydantic-settings = "^2.7.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
aiosqlite = "^0.21.0"
alembic = "^1.14.0"
aiosmtplib = "^4.0.0"
jinja2 = "^3.1.5"
botocore = "^1.35.99"
aioboto3 = "^13.4.0"
pillow = "^11.1.0"
email-validator = "^2.2.0"
python-multipart = "^0.0.20"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
